# Generated by Django 4.2.4 on 2023-08-15 21:42

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('account', '0002_remove_user_phone1_remove_user_phone2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_registrar',
        ),
        migrations.AddField(
            model_name='user',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chiefs', to='management.commune', verbose_name='Commune in charge'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_chief_commune',
            field=models.BooleanField(default=False, verbose_name='Is Chief Commune'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_nationalAdministrator',
            field=models.BooleanField(default=False, verbose_name='Is National Administrator'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
    ]
