# Generated by Django 4.2.4 on 2023-09-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredidcard',
            name='takenCount',
            field=models.CharField(choices=[('', 'Select Parent'), ('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], default='', max_length=10, verbose_name='Taken Count'),
        ),
    ]
