# Generated by Django 4.2.4 on 2023-08-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_citizen_recorded_by_idcardregistration_recorded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colline',
            name='colline_name',
            field=models.CharField(max_length=50, verbose_name='Colline Name'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='commune_name',
            field=models.CharField(max_length=50, verbose_name='Commune Name'),
        ),
    ]
