# Generated by Django 4.2.4 on 2023-08-16 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0003_alter_colline_colline_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idcardregistration',
            name='data_hash',
        ),
        migrations.RemoveField(
            model_name='idcardregistration',
            name='signature',
        ),
        migrations.CreateModel(
            name='RegisteredIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, verbose_name='ID Number')),
                ('is_taken', models.BooleanField(default=False, verbose_name='Is taken?')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Date created')),
                ('taken_date', models.DateField(verbose_name='Date taken')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.citizen', verbose_name='Citizen')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
