# Generated by Django 4.2.4 on 2023-09-09 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_rejectedidcardapplication_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='citizen/images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Citizen Image'),
        ),
    ]
