# Generated by Django 4.2.4 on 2023-08-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_idcardregistration_data_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, unique=True, verbose_name='Service Title')),
                ('requirements', models.TextField(verbose_name='Requirements')),
            ],
        ),
    ]
