# Generated by Django 4.2.4 on 2023-09-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_citizen_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostidcardreport',
            name='status',
            field=models.CharField(choices=[('', 'Select Status'), ('Waiting', 'Waiting'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Waiting', max_length=20, verbose_name='Status'),
        ),
    ]
