# Generated by Django 4.2.5 on 2023-09-26 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_lostidcardreport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_image', models.ImageField(upload_to='citizen/nid_card_qr_codes/')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Generated Date')),
                ('citizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nid_card', to='management.citizen', verbose_name='NID Card')),
            ],
        ),
    ]
